### ISSUE TITLE
Cutscenes freezing

### ISSUE THREAD

**Issue by pughead** [baggyg/BendyVR#32] opened 2024-11-23 19:29 UTC
I don't know if this mod will ever get updated again, but the update for Bendy and the Ink Machine in October broke the mod to where you can't move at all after any cutscene plays. The mod refuses to open when I revert back to another version of the game, making it almost impossible to play. The mod is really good but the new Bendy update messed it up basically. I hope this can get fixed.

**Comment by pughead** [comment] 2024-11-23 19:31
I just read the other issue under this one I typed this without realizing that someone else already posted about this issue, Sorry

**Comment by baggyg** [comment] 2024-11-26 12:55
Duplicate of #31

**Closed by baggyg** 2024-11-26 12:55 UTC
